######################## default configuration ####################
baseURL = "https://example.com"
title = "Timothé Moessner"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins

[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Accueil"
URL = "#home"
weight = 1

[[menu.main]]
name = "À propos de moi"
URL = "#about"
weight = 2

[[menu.main]]
name = "Éxpériences"
URL = "#experience"
weight = 3

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 4

#################### default parameters ################################
[params]
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"
copyright = "Copyright Timothé Moessner &copy;"
# Meta data
description = "Personal Resume"
author = "Quentin Moessner"
favicon = "images/favicon.ico"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################


[[params.social]]
icon = "fas fa-phone"
link = "tel:0669621361"
content = "06 69 62 13 61"
alt = "06 69 62 13 61"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:moessner.timothe@gmail.com"
content = "moessner.timothe@gmail.com"
alt = "moessner.timothe@gmail.com"

[[params.social]]
icon = "fas fa-home"
link = "#"
content = "16 rue de Bruebach <br /> 68440 Eschentzwiller"
alt = "16 Rue de Bruebach 68440 Eschentzwiller"


contentDir = "content/english"
weight = 1
home = "Home"
